version: '3.7'

services:

#  app:
#    build: .
#    environment:
#      OTLP_ENDPOINT: 'http://localhost:4317'
#      OTEL_JAEGER_COLLECTOR_HOST_PORT: jaeger:14250
#      OTEL_ELASTIC_SERVER_URL: 'http://elastic_apm:8200'
#      OPENTRACING_MODE: 1
#      START_COMMAND: python src/otel_emit.py

  publisher:
    build: .
    environment:
      OTLP_ENDPOINT: 'http://localhost:4317'
      OTEL_JAEGER_COLLECTOR_HOST_PORT: jaeger:14250
      SUPERVISOR_JAEGER_COLLECTOR_HOST_PORT: jaeger:14250
      OTEL_ELASTIC_SERVER_URL: 'http://elastic_apm:8200'
      START_COMMAND: python src/otel_publish.py
      JAEGER_MODE: 1
    volumes:
      - ./src:/app/src
    depends_on:
      rabbitmq:
        condition: service_healthy

  subscriber:
    build: .
    environment:
      OTLP_ENDPOINT: 'http://localhost:4317'
      OTEL_JAEGER_COLLECTOR_HOST_PORT: jaeger:14250
      SUPERVISOR_JAEGER_COLLECTOR_HOST_PORT: jaeger:14250
      OTEL_ELASTIC_SERVER_URL: 'http://elastic_apm:8200'
      START_COMMAND: python src/otel_subscribe.py
      JAEGER_MODE: 1
    volumes:
      - ./src:/app/src
    depends_on:
      rabbitmq:
        condition: service_healthy

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      cluster.name: docker-cluster
      cluster.routing.allocation.disk.threshold_enabled: "false"
      discovery.type: single-node
      ES_JAVA_OPTS: '-XX:UseAVX=2 -Xms1g -Xmx1g'
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  elastic_apm:
    image: docker.elastic.co/apm/apm-server:7.12.1
    ports:
      - 8200:8200
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elastic:9200"]
    depends_on:
      elastic:
        condition: service_healthy
      kibana:
        condition: service_healthy
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    environment:
      ELASTICSEARCH_URL: 'http://elastic:9200'
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
    depends_on:
      elastic:
        condition: service_healthy
    ports:
      - 5601:5601
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - 16686:16686
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elastic:9200
    depends_on:
      elastic:
        condition: service_healthy


  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15670:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
