receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  # for memory_limiter and batch the values are an approximation based on the 1G memory allocated in nimbus
  # they should be amended if required.
  memory_limiter:
    check_interval: 1s
    limit_mib: 200
    spike_limit_mib: 50
  batch:
    send_batch_size: 1024
    timeout: 250ms
    send_batch_max_size: 2000

exporters:
  jaeger:
    insecure: true
    endpoint: "${OTEL_JAEGER_COLLECTOR_HOST_PORT}"
  elastic:
    apm_server_url: "${OTEL_ELASTIC_SERVER_URL}"
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - jaeger
        - elastic
        - logging
